# Generated by Django 5.1.7 on 2025-03-31 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0002_attendance_complaint_fee_visitor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitor',
            old_name='name',
            new_name='visitor_name',
        ),
        migrations.AddField(
            model_name='visitor',
            name='warden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitors', to=settings.AUTH_USER_MODEL),
        ),
    ]
